/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BundleParsedItemsInner {
    'uuid'?: string;
    'name'?: string;
    'image'?: string;
    'type'?: string;
    'amount'?: number;
    'discountPercent'?: number;
    'basePrice'?: number;
    'discountedPrice'?: number;
    'promoItem'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number",
            "format": ""
        },
        {
            "name": "discountPercent",
            "baseName": "discount_percent",
            "type": "number",
            "format": ""
        },
        {
            "name": "basePrice",
            "baseName": "base_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "discountedPrice",
            "baseName": "discounted_price",
            "type": "number",
            "format": ""
        },
        {
            "name": "promoItem",
            "baseName": "promo_item",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BundleParsedItemsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

