/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BySeasonActRankWinsInner } from '../models/BySeasonActRankWinsInner';
import { HttpFile } from '../http/http';

export class BySeason {
    'error'?: boolean | null;
    'wins'?: number;
    'numberOfGames'?: number;
    'finalRank'?: number;
    'finalRankPatched'?: string;
    'actRankWins'?: Array<BySeasonActRankWinsInner>;
    'old'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "wins",
            "baseName": "wins",
            "type": "number",
            "format": ""
        },
        {
            "name": "numberOfGames",
            "baseName": "number_of_games",
            "type": "number",
            "format": ""
        },
        {
            "name": "finalRank",
            "baseName": "final_rank",
            "type": "number",
            "format": ""
        },
        {
            "name": "finalRankPatched",
            "baseName": "final_rank_patched",
            "type": "string",
            "format": ""
        },
        {
            "name": "actRankWins",
            "baseName": "act_rank_wins",
            "type": "Array<BySeasonActRankWinsInner>",
            "format": ""
        },
        {
            "name": "old",
            "baseName": "old",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BySeason.attributeTypeMap;
    }

    public constructor() {
    }
}

