/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LeaderboardInner {
    'playerCardID'?: string;
    'titleID'?: string;
    'isBanned'?: boolean;
    'isAnonymized'?: boolean;
    'puuid'?: string;
    'gameName'?: string;
    'tagLine'?: string;
    'leaderboardRank'?: number;
    'rankedRating'?: number;
    'numberOfWins'?: number;
    'competitiveTier'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playerCardID",
            "baseName": "PlayerCardID",
            "type": "string",
            "format": ""
        },
        {
            "name": "titleID",
            "baseName": "TitleID",
            "type": "string",
            "format": ""
        },
        {
            "name": "isBanned",
            "baseName": "IsBanned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isAnonymized",
            "baseName": "IsAnonymized",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "puuid",
            "baseName": "puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "gameName",
            "baseName": "gameName",
            "type": "string",
            "format": ""
        },
        {
            "name": "tagLine",
            "baseName": "tagLine",
            "type": "string",
            "format": ""
        },
        {
            "name": "leaderboardRank",
            "baseName": "leaderboardRank",
            "type": "number",
            "format": ""
        },
        {
            "name": "rankedRating",
            "baseName": "rankedRating",
            "type": "number",
            "format": ""
        },
        {
            "name": "numberOfWins",
            "baseName": "numberOfWins",
            "type": "number",
            "format": ""
        },
        {
            "name": "competitiveTier",
            "baseName": "competitiveTier",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LeaderboardInner.attributeTypeMap;
    }

    public constructor() {
    }
}

