/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum Maps {
    Ascent = 'Ascent',
    Split = 'Split',
    Fracture = 'Fracture',
    Bind = 'Bind',
    Breeze = 'Breeze',
    District = 'District',
    Kasbah = 'Kasbah',
    Piazza = 'Piazza',
    Lotus = 'Lotus',
    Pearl = 'Pearl',
    Icebox = 'Icebox',
    Haven = 'Haven'
}
