/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlayerStatsInnerDamageEventsInner {
    'receiverPuuid'?: string;
    'receiverDisplayName'?: string;
    'receiverTeam'?: string;
    'bodyshots'?: number;
    'damage'?: number;
    'headshots'?: number;
    'legshots'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "receiverPuuid",
            "baseName": "receiver_puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "receiverDisplayName",
            "baseName": "receiver_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "receiverTeam",
            "baseName": "receiver_team",
            "type": "string",
            "format": ""
        },
        {
            "name": "bodyshots",
            "baseName": "bodyshots",
            "type": "number",
            "format": ""
        },
        {
            "name": "damage",
            "baseName": "damage",
            "type": "number",
            "format": ""
        },
        {
            "name": "headshots",
            "baseName": "headshots",
            "type": "number",
            "format": ""
        },
        {
            "name": "legshots",
            "baseName": "legshots",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlayerStatsInnerDamageEventsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

