/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlayerStatsInnerKillEventsInnerAssistantsInner {
    'assistantPuuid'?: string;
    'assistantDisplayName'?: string;
    'assistantTeam'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assistantPuuid",
            "baseName": "assistant_puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "assistantDisplayName",
            "baseName": "assistant_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "assistantTeam",
            "baseName": "assistant_team",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlayerStatsInnerKillEventsInnerAssistantsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

