/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Maps } from '../models/Maps';
import { MatchMetadataPremierInfo } from '../models/MatchMetadataPremierInfo';
import { ModeIds } from '../models/ModeIds';
import { Modes } from '../models/Modes';
import { Regions } from '../models/Regions';
import { HttpFile } from '../http/http';

export class MatchMetadata {
    'map'?: Maps;
    'gameVersion'?: string;
    'gameLength'?: number;
    'gameStart'?: number;
    'gameStartPatched'?: string;
    'roundsPlayed'?: number;
    'mode'?: Modes;
    'modeId'?: ModeIds;
    'queue'?: string;
    'seasonId'?: string;
    'platform'?: string;
    'matchid'?: string;
    'premierInfo'?: MatchMetadataPremierInfo;
    'region'?: Regions;
    'cluster'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "map",
            "baseName": "map",
            "type": "Maps",
            "format": ""
        },
        {
            "name": "gameVersion",
            "baseName": "game_version",
            "type": "string",
            "format": ""
        },
        {
            "name": "gameLength",
            "baseName": "game_length",
            "type": "number",
            "format": ""
        },
        {
            "name": "gameStart",
            "baseName": "game_start",
            "type": "number",
            "format": ""
        },
        {
            "name": "gameStartPatched",
            "baseName": "game_start_patched",
            "type": "string",
            "format": ""
        },
        {
            "name": "roundsPlayed",
            "baseName": "rounds_played",
            "type": "number",
            "format": ""
        },
        {
            "name": "mode",
            "baseName": "mode",
            "type": "Modes",
            "format": ""
        },
        {
            "name": "modeId",
            "baseName": "mode_id",
            "type": "ModeIds",
            "format": ""
        },
        {
            "name": "queue",
            "baseName": "queue",
            "type": "string",
            "format": ""
        },
        {
            "name": "seasonId",
            "baseName": "season_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchid",
            "baseName": "matchid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "premierInfo",
            "baseName": "premier_info",
            "type": "MatchMetadataPremierInfo",
            "format": ""
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "Regions",
            "format": ""
        },
        {
            "name": "cluster",
            "baseName": "cluster",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchMetadata.attributeTypeMap;
    }

    public constructor() {
    }
}



