/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchRoundsInnerPlayerStatsInnerEconomyArmor } from '../models/MatchRoundsInnerPlayerStatsInnerEconomyArmor';
import { MatchRoundsInnerPlayerStatsInnerEconomyWeapon } from '../models/MatchRoundsInnerPlayerStatsInnerEconomyWeapon';
import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlayerStatsInnerEconomy {
    'loadoutValue'?: number;
    'weapon'?: MatchRoundsInnerPlayerStatsInnerEconomyWeapon;
    'armor'?: MatchRoundsInnerPlayerStatsInnerEconomyArmor;
    'remaining'?: number;
    'spent'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "loadoutValue",
            "baseName": "loadout_value",
            "type": "number",
            "format": ""
        },
        {
            "name": "weapon",
            "baseName": "weapon",
            "type": "MatchRoundsInnerPlayerStatsInnerEconomyWeapon",
            "format": ""
        },
        {
            "name": "armor",
            "baseName": "armor",
            "type": "MatchRoundsInnerPlayerStatsInnerEconomyArmor",
            "format": ""
        },
        {
            "name": "remaining",
            "baseName": "remaining",
            "type": "number",
            "format": ""
        },
        {
            "name": "spent",
            "baseName": "spent",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlayerStatsInnerEconomy.attributeTypeMap;
    }

    public constructor() {
    }
}

