/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchRoundsInnerPlantEventsPlantLocation } from '../models/MatchRoundsInnerPlantEventsPlantLocation';
import { MatchRoundsInnerPlantEventsPlantedBy } from '../models/MatchRoundsInnerPlantEventsPlantedBy';
import { MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner } from '../models/MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner';
import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlantEvents {
    'plantLocation'?: MatchRoundsInnerPlantEventsPlantLocation | null;
    'plantedBy'?: MatchRoundsInnerPlantEventsPlantedBy | null;
    'plantSite'?: string | null;
    'plantTimeInRound'?: number | null;
    'playerLocationsOnPlant'?: Array<MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "plantLocation",
            "baseName": "plant_location",
            "type": "MatchRoundsInnerPlantEventsPlantLocation",
            "format": ""
        },
        {
            "name": "plantedBy",
            "baseName": "planted_by",
            "type": "MatchRoundsInnerPlantEventsPlantedBy",
            "format": ""
        },
        {
            "name": "plantSite",
            "baseName": "plant_site",
            "type": "string",
            "format": ""
        },
        {
            "name": "plantTimeInRound",
            "baseName": "plant_time_in_round",
            "type": "number",
            "format": ""
        },
        {
            "name": "playerLocationsOnPlant",
            "baseName": "player_locations_on_plant",
            "type": "Array<MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlantEvents.attributeTypeMap;
    }

    public constructor() {
    }
}

