/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner } from '../models/MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner';
import { MatchRoundsInnerPlayerStatsInnerKillEventsInnerAssistantsInner } from '../models/MatchRoundsInnerPlayerStatsInnerKillEventsInnerAssistantsInner';
import { MatchRoundsInnerPlayerStatsInnerKillEventsInnerDamageWeaponAssets } from '../models/MatchRoundsInnerPlayerStatsInnerKillEventsInnerDamageWeaponAssets';
import { MatchRoundsInnerPlayerStatsInnerKillEventsInnerVictimDeathLocation } from '../models/MatchRoundsInnerPlayerStatsInnerKillEventsInnerVictimDeathLocation';
import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlayerStatsInnerKillEventsInner {
    'killTimeInRound'?: number;
    'killTimeInMatch'?: number;
    'killerPuuid'?: string;
    'killerDisplayName'?: string;
    'killerTeam'?: string;
    'victimPuuid'?: string;
    'victimDisplayName'?: string;
    'victimTeam'?: string;
    'victimDeathLocation'?: MatchRoundsInnerPlayerStatsInnerKillEventsInnerVictimDeathLocation;
    'damageWeaponId'?: string;
    'damageWeaponName'?: string;
    'damageWeaponAssets'?: MatchRoundsInnerPlayerStatsInnerKillEventsInnerDamageWeaponAssets;
    'secondaryFireMode'?: boolean;
    'playerLocationsOnKill'?: Array<MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner>;
    'assistants'?: Array<MatchRoundsInnerPlayerStatsInnerKillEventsInnerAssistantsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "killTimeInRound",
            "baseName": "kill_time_in_round",
            "type": "number",
            "format": ""
        },
        {
            "name": "killTimeInMatch",
            "baseName": "kill_time_in_match",
            "type": "number",
            "format": ""
        },
        {
            "name": "killerPuuid",
            "baseName": "killer_puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "killerDisplayName",
            "baseName": "killer_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "killerTeam",
            "baseName": "killer_team",
            "type": "string",
            "format": ""
        },
        {
            "name": "victimPuuid",
            "baseName": "victim_puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "victimDisplayName",
            "baseName": "victim_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "victimTeam",
            "baseName": "victim_team",
            "type": "string",
            "format": ""
        },
        {
            "name": "victimDeathLocation",
            "baseName": "victim_death_location",
            "type": "MatchRoundsInnerPlayerStatsInnerKillEventsInnerVictimDeathLocation",
            "format": ""
        },
        {
            "name": "damageWeaponId",
            "baseName": "damage_weapon_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "damageWeaponName",
            "baseName": "damage_weapon_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "damageWeaponAssets",
            "baseName": "damage_weapon_assets",
            "type": "MatchRoundsInnerPlayerStatsInnerKillEventsInnerDamageWeaponAssets",
            "format": ""
        },
        {
            "name": "secondaryFireMode",
            "baseName": "secondary_fire_mode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "playerLocationsOnKill",
            "baseName": "player_locations_on_kill",
            "type": "Array<MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner>",
            "format": ""
        },
        {
            "name": "assistants",
            "baseName": "assistants",
            "type": "Array<MatchRoundsInnerPlayerStatsInnerKillEventsInnerAssistantsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlayerStatsInnerKillEventsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

