/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlayerStatsInnerAbilityCasts {
    'cCasts'?: number | null;
    'qCasts'?: number | null;
    'eCasts'?: number | null;
    'xCasts'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cCasts",
            "baseName": "c_casts",
            "type": "number",
            "format": ""
        },
        {
            "name": "qCasts",
            "baseName": "q_casts",
            "type": "number",
            "format": ""
        },
        {
            "name": "eCasts",
            "baseName": "e_casts",
            "type": "number",
            "format": ""
        },
        {
            "name": "xCasts",
            "baseName": "x_casts",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlayerStatsInnerAbilityCasts.attributeTypeMap;
    }

    public constructor() {
    }
}

