/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Player } from '../models/Player';
import { HttpFile } from '../http/http';

export class MatchPlayers {
    'allPlayers'?: Array<Player>;
    'red'?: Array<Player>;
    'blue'?: Array<Player>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "allPlayers",
            "baseName": "all_players",
            "type": "Array<Player>",
            "format": ""
        },
        {
            "name": "red",
            "baseName": "red",
            "type": "Array<Player>",
            "format": ""
        },
        {
            "name": "blue",
            "baseName": "blue",
            "type": "Array<Player>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchPlayers.attributeTypeMap;
    }

    public constructor() {
    }
}

