/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInnerLocation } from '../models/MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInnerLocation';
import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner {
    'playerPuuid'?: string;
    'playerDisplayName'?: string;
    'playerTeam'?: string;
    'location'?: MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInnerLocation;
    'viewRadians'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playerPuuid",
            "baseName": "player_puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerDisplayName",
            "baseName": "player_display_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerTeam",
            "baseName": "player_team",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInnerLocation",
            "format": ""
        },
        {
            "name": "viewRadians",
            "baseName": "view_radians",
            "type": "number",
            "format": "double"
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlantEventsPlayerLocationsOnPlantInner.attributeTypeMap;
    }

    public constructor() {
    }
}

