/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class MatchMetadataPremierInfo {
    'tournamentId'?: string | null;
    'matchupId'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tournamentId",
            "baseName": "tournament_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "matchupId",
            "baseName": "matchup_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchMetadataPremierInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

