/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MatchRoundsInnerPlayerStatsInnerEconomyWeaponAssets } from '../models/MatchRoundsInnerPlayerStatsInnerEconomyWeaponAssets';
import { HttpFile } from '../http/http';

export class MatchRoundsInnerPlayerStatsInnerEconomyWeapon {
    'id'?: string;
    'name'?: string;
    'assets'?: MatchRoundsInnerPlayerStatsInnerEconomyWeaponAssets;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "MatchRoundsInnerPlayerStatsInnerEconomyWeaponAssets",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MatchRoundsInnerPlayerStatsInnerEconomyWeapon.attributeTypeMap;
    }

    public constructor() {
    }
}

