/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum Modes {
    Competitive = 'Competitive',
    CustomGame = 'Custom Game',
    Deathmatch = 'Deathmatch',
    Escalation = 'Escalation',
    TeamDeathmatch = 'Team Deathmatch',
    NewMap = 'New Map',
    Replication = 'Replication',
    SnowballFight = 'Snowball Fight',
    SpikeRush = 'Spike Rush',
    Swiftplay = 'Swiftplay',
    Unrated = 'Unrated'
}
