/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum ModeIds {
    Competitive = 'competitive',
    Custom = 'custom',
    Deathmatch = 'deathmatch',
    Ggteam = 'ggteam',
    Hurm = 'hurm',
    Newmap = 'newmap',
    Onefa = 'onefa',
    Snowball = 'snowball',
    Spikerush = 'spikerush',
    Swiftplay = 'swiftplay',
    Unrated = 'unrated'
}
