/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlayerPlatform } from '../models/PlayerPlatform';
import { PlayerSessionPlaytime } from '../models/PlayerSessionPlaytime';
import { HttpFile } from '../http/http';

export class Observer {
    'puuid'?: string;
    'name'?: string;
    'tag'?: string;
    'platform'?: PlayerPlatform;
    'sessionPlaytime'?: PlayerSessionPlaytime;
    'team'?: string;
    'level'?: number;
    'playerCard'?: string;
    'playerTitle'?: string;
    'partyId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "puuid",
            "baseName": "puuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PlayerPlatform",
            "format": ""
        },
        {
            "name": "sessionPlaytime",
            "baseName": "session_playtime",
            "type": "PlayerSessionPlaytime",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "playerCard",
            "baseName": "player_card",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "playerTitle",
            "baseName": "player_title",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": "uuid"
        }    ];

    static getAttributeTypeMap() {
        return Observer.attributeTypeMap;
    }

    public constructor() {
    }
}

