/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlayerAbilityCasts } from '../models/PlayerAbilityCasts';
import { PlayerAssets } from '../models/PlayerAssets';
import { PlayerBehaviour } from '../models/PlayerBehaviour';
import { PlayerEconomy } from '../models/PlayerEconomy';
import { PlayerPlatform } from '../models/PlayerPlatform';
import { PlayerSessionPlaytime } from '../models/PlayerSessionPlaytime';
import { PlayerStats } from '../models/PlayerStats';
import { HttpFile } from '../http/http';

export class Player {
    'puuid'?: string;
    'name'?: string;
    'tag'?: string;
    'team'?: string;
    'level'?: number;
    'character'?: string;
    'currenttier'?: number;
    'currenttierPatched'?: string;
    'playerCard'?: string;
    'playerTitle'?: string;
    'partyId'?: string;
    'sessionPlaytime'?: PlayerSessionPlaytime;
    'assets'?: PlayerAssets;
    'behaviour'?: PlayerBehaviour;
    'platform'?: PlayerPlatform;
    'abilityCasts'?: PlayerAbilityCasts;
    'stats'?: PlayerStats;
    'economy'?: PlayerEconomy;
    'damageMade'?: number;
    'damageReceived'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "puuid",
            "baseName": "puuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "team",
            "baseName": "team",
            "type": "string",
            "format": ""
        },
        {
            "name": "level",
            "baseName": "level",
            "type": "number",
            "format": ""
        },
        {
            "name": "character",
            "baseName": "character",
            "type": "string",
            "format": ""
        },
        {
            "name": "currenttier",
            "baseName": "currenttier",
            "type": "number",
            "format": ""
        },
        {
            "name": "currenttierPatched",
            "baseName": "currenttier_patched",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerCard",
            "baseName": "player_card",
            "type": "string",
            "format": ""
        },
        {
            "name": "playerTitle",
            "baseName": "player_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "partyId",
            "baseName": "party_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "sessionPlaytime",
            "baseName": "session_playtime",
            "type": "PlayerSessionPlaytime",
            "format": ""
        },
        {
            "name": "assets",
            "baseName": "assets",
            "type": "PlayerAssets",
            "format": ""
        },
        {
            "name": "behaviour",
            "baseName": "behaviour",
            "type": "PlayerBehaviour",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "PlayerPlatform",
            "format": ""
        },
        {
            "name": "abilityCasts",
            "baseName": "ability_casts",
            "type": "PlayerAbilityCasts",
            "format": ""
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "PlayerStats",
            "format": ""
        },
        {
            "name": "economy",
            "baseName": "economy",
            "type": "PlayerEconomy",
            "format": ""
        },
        {
            "name": "damageMade",
            "baseName": "damage_made",
            "type": "number",
            "format": ""
        },
        {
            "name": "damageReceived",
            "baseName": "damage_received",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Player.attributeTypeMap;
    }

    public constructor() {
    }
}

