/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PlayerAssetsAgent {
    'small'?: string;
    'full'?: string;
    'bust'?: string;
    'killfeed'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "small",
            "baseName": "small",
            "type": "string",
            "format": ""
        },
        {
            "name": "full",
            "baseName": "full",
            "type": "string",
            "format": ""
        },
        {
            "name": "bust",
            "baseName": "bust",
            "type": "string",
            "format": ""
        },
        {
            "name": "killfeed",
            "baseName": "killfeed",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerAssetsAgent.attributeTypeMap;
    }

    public constructor() {
    }
}

