/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlayerEconomyLoadoutValue } from '../models/PlayerEconomyLoadoutValue';
import { PlayerEconomySpent } from '../models/PlayerEconomySpent';
import { HttpFile } from '../http/http';

export class PlayerEconomy {
    'spent'?: PlayerEconomySpent;
    'loadoutValue'?: PlayerEconomyLoadoutValue;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "spent",
            "baseName": "spent",
            "type": "PlayerEconomySpent",
            "format": ""
        },
        {
            "name": "loadoutValue",
            "baseName": "loadout_value",
            "type": "PlayerEconomyLoadoutValue",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerEconomy.attributeTypeMap;
    }

    public constructor() {
    }
}

