/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PlayerAssetsCard {
    'small'?: string;
    'large'?: string;
    'wide'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "small",
            "baseName": "small",
            "type": "string",
            "format": ""
        },
        {
            "name": "large",
            "baseName": "large",
            "type": "string",
            "format": ""
        },
        {
            "name": "wide",
            "baseName": "wide",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerAssetsCard.attributeTypeMap;
    }

    public constructor() {
    }
}

