/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlayerBehaviourFriendlyFire } from '../models/PlayerBehaviourFriendlyFire';
import { HttpFile } from '../http/http';

export class PlayerBehaviour {
    'afkRounds'?: number;
    'friendlyFire'?: PlayerBehaviourFriendlyFire;
    'roundsInSpawn'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "afkRounds",
            "baseName": "afk_rounds",
            "type": "number",
            "format": ""
        },
        {
            "name": "friendlyFire",
            "baseName": "friendly_fire",
            "type": "PlayerBehaviourFriendlyFire",
            "format": ""
        },
        {
            "name": "roundsInSpawn",
            "baseName": "rounds_in_spawn",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerBehaviour.attributeTypeMap;
    }

    public constructor() {
    }
}

