/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PlayerPlatformOs } from '../models/PlayerPlatformOs';
import { HttpFile } from '../http/http';

export class PlayerPlatform {
    'type'?: string;
    'os'?: PlayerPlatformOs;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "os",
            "baseName": "os",
            "type": "PlayerPlatformOs",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PlayerPlatform.attributeTypeMap;
    }

    public constructor() {
    }
}

