/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum Seasons {
    E1a1 = 'e1a1',
    E1a2 = 'e1a2',
    E1a3 = 'e1a3',
    E2a1 = 'e2a1',
    E2a2 = 'e2a2',
    E2a3 = 'e2a3',
    E3a1 = 'e3a1',
    E3a2 = 'e3a2',
    E3a3 = 'e3a3',
    E4a1 = 'e4a1',
    E4a2 = 'e4a2',
    E4a3 = 'e4a3',
    E5a1 = 'e5a1',
    E5a2 = 'e5a2',
    E5a3 = 'e5a3',
    E6a1 = 'e6a1',
    E6a2 = 'e6a2',
    E6a3 = 'e6a3',
    E7a1 = 'e7a1',
    E7a2 = 'e7a2',
    E7a3 = 'e7a3'
}
