/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusInnerTitlesInner } from '../models/StatusInnerTitlesInner';
import { StatusInnerUpdatesInner } from '../models/StatusInnerUpdatesInner';
import { HttpFile } from '../http/http';

export class StatusInner {
    'createdAt'?: string;
    'archiveAt'?: string | null;
    'updates'?: Array<StatusInnerUpdatesInner>;
    'platforms'?: Array<string>;
    'updatedAt'?: string | null;
    'id'?: number;
    'titles'?: Array<StatusInnerTitlesInner>;
    'maintenanceStatus'?: string;
    'incidentSeverity'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "archiveAt",
            "baseName": "archive_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updates",
            "baseName": "updates",
            "type": "Array<StatusInnerUpdatesInner>",
            "format": ""
        },
        {
            "name": "platforms",
            "baseName": "platforms",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "titles",
            "baseName": "titles",
            "type": "Array<StatusInnerTitlesInner>",
            "format": ""
        },
        {
            "name": "maintenanceStatus",
            "baseName": "maintenance_status",
            "type": "string",
            "format": ""
        },
        {
            "name": "incidentSeverity",
            "baseName": "incident_severity",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatusInner.attributeTypeMap;
    }

    public constructor() {
    }
}

