/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusInnerUpdatesInnerTranslationsInner } from '../models/StatusInnerUpdatesInnerTranslationsInner';
import { HttpFile } from '../http/http';

export class StatusInnerUpdatesInner {
    'createdAt'?: string;
    'updatedAt'?: string | null;
    'publish'?: boolean;
    'id'?: number;
    'translations'?: Array<StatusInnerUpdatesInnerTranslationsInner>;
    'publishLocations'?: Array<string>;
    'author'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "string",
            "format": ""
        },
        {
            "name": "publish",
            "baseName": "publish",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "translations",
            "baseName": "translations",
            "type": "Array<StatusInnerUpdatesInnerTranslationsInner>",
            "format": ""
        },
        {
            "name": "publishLocations",
            "baseName": "publish_locations",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return StatusInnerUpdatesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

