/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TeamRoaster } from '../models/TeamRoaster';
import { HttpFile } from '../http/http';

export class Team {
    'hasWon'?: boolean | null;
    'roundsWon'?: number | null;
    'roundsLost'?: number | null;
    'roaster'?: TeamRoaster | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hasWon",
            "baseName": "has_won",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "roundsWon",
            "baseName": "rounds_won",
            "type": "number",
            "format": ""
        },
        {
            "name": "roundsLost",
            "baseName": "rounds_lost",
            "type": "number",
            "format": ""
        },
        {
            "name": "roaster",
            "baseName": "roaster",
            "type": "TeamRoaster",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Team.attributeTypeMap;
    }

    public constructor() {
    }
}

