/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export enum TiersOld {
    Unrated = 'Unrated',
    Unknown1 = 'Unknown 1',
    Unknown2 = 'Unknown 2',
    Iron1 = 'Iron 1',
    Iron2 = 'Iron 2',
    Iron3 = 'Iron 3',
    Bronze1 = 'Bronze 1',
    Bronze2 = 'Bronze 2',
    Bronze3 = 'Bronze 3',
    Silver1 = 'Silver 1',
    Silver2 = 'Silver 2',
    Silver3 = 'Silver 3',
    Gold1 = 'Gold 1',
    Gold2 = 'Gold 2',
    Gold3 = 'Gold 3',
    Platinum1 = 'Platinum 1',
    Platinum2 = 'Platinum 2',
    Platinum3 = 'Platinum 3',
    Diamond1 = 'Diamond 1',
    Diamond2 = 'Diamond 2',
    Diamond3 = 'Diamond 3',
    Immortal1 = 'Immortal 1',
    Immortal2 = 'Immortal 2',
    Immortal3 = 'Immortal 3',
    Radiant = 'Radiant'
}
