/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V1esportscheduleitemMatchGameType {
    'type'?: V1esportscheduleitemMatchGameTypeTypeEnum | null;
    'count'?: number | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "V1esportscheduleitemMatchGameTypeTypeEnum",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1esportscheduleitemMatchGameType.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum V1esportscheduleitemMatchGameTypeTypeEnum {
    PlayAll = 'playAll',
    BestOf = 'bestOf'
}

