/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1LifetimeMmrHistoryItemSeason } from '../models/V1LifetimeMmrHistoryItemSeason';
import { V1QueueStatusDataInnerMapsInnerMap } from '../models/V1QueueStatusDataInnerMapsInnerMap';
import { V1QueueStatusDataInnerSkillDisparityInnerMaxTier } from '../models/V1QueueStatusDataInnerSkillDisparityInnerMaxTier';
import { HttpFile } from '../http/http';

export class V1LifetimeMmrHistoryItem {
    'matchId'?: string;
    'tier'?: V1QueueStatusDataInnerSkillDisparityInnerMaxTier;
    'map'?: V1QueueStatusDataInnerMapsInnerMap;
    'season'?: V1LifetimeMmrHistoryItemSeason;
    'rankingInTier'?: number;
    'lastMmrChange'?: number;
    'elo'?: number;
    'date'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "matchId",
            "baseName": "match_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "V1QueueStatusDataInnerSkillDisparityInnerMaxTier",
            "format": ""
        },
        {
            "name": "map",
            "baseName": "map",
            "type": "V1QueueStatusDataInnerMapsInnerMap",
            "format": ""
        },
        {
            "name": "season",
            "baseName": "season",
            "type": "V1LifetimeMmrHistoryItemSeason",
            "format": ""
        },
        {
            "name": "rankingInTier",
            "baseName": "ranking_in_tier",
            "type": "number",
            "format": ""
        },
        {
            "name": "lastMmrChange",
            "baseName": "last_mmr_change",
            "type": "number",
            "format": ""
        },
        {
            "name": "elo",
            "baseName": "elo",
            "type": "number",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return V1LifetimeMmrHistoryItem.attributeTypeMap;
    }

    public constructor() {
    }
}

