/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Seasons } from '../models/Seasons';
import { HttpFile } from '../http/http';

export class V1LifetimeMmrHistoryItemSeason {
    'id'?: string;
    '_short'?: Seasons;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "_short",
            "baseName": "short",
            "type": "Seasons",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1LifetimeMmrHistoryItemSeason.attributeTypeMap;
    }

    public constructor() {
    }
}



