/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1LifetimeMatchesResults } from '../models/V1LifetimeMatchesResults';
import { V1LifetimeMmrHistoryItem } from '../models/V1LifetimeMmrHistoryItem';
import { HttpFile } from '../http/http';

export class V1LifetimeMmrHistory {
    'status'?: number;
    'name'?: string;
    'tag'?: string;
    'results'?: V1LifetimeMatchesResults;
    'data'?: Array<V1LifetimeMmrHistoryItem>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "V1LifetimeMatchesResults",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<V1LifetimeMmrHistoryItem>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1LifetimeMmrHistory.attributeTypeMap;
    }

    public constructor() {
    }
}

