/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1mmrhDataInnerImages } from '../models/V1mmrhDataInnerImages';
import { V1mmrhDataInnerMap } from '../models/V1mmrhDataInnerMap';
import { HttpFile } from '../http/http';

export class V1mmrhDataInner {
    'currenttier'?: number;
    'currenttierPatched'?: string;
    'images'?: V1mmrhDataInnerImages;
    'matchId'?: string;
    'map'?: V1mmrhDataInnerMap;
    'seasonId'?: string;
    'rankingInTier'?: number;
    'mmrChangeToLastGame'?: number;
    'elo'?: number;
    'date'?: string;
    'dateRaw'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "currenttier",
            "baseName": "currenttier",
            "type": "number",
            "format": ""
        },
        {
            "name": "currenttierPatched",
            "baseName": "currenttier_patched",
            "type": "string",
            "format": ""
        },
        {
            "name": "images",
            "baseName": "images",
            "type": "V1mmrhDataInnerImages",
            "format": ""
        },
        {
            "name": "matchId",
            "baseName": "match_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "map",
            "baseName": "map",
            "type": "V1mmrhDataInnerMap",
            "format": ""
        },
        {
            "name": "seasonId",
            "baseName": "season_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "rankingInTier",
            "baseName": "ranking_in_tier",
            "type": "number",
            "format": ""
        },
        {
            "name": "mmrChangeToLastGame",
            "baseName": "mmr_change_to_last_game",
            "type": "number",
            "format": ""
        },
        {
            "name": "elo",
            "baseName": "elo",
            "type": "number",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "dateRaw",
            "baseName": "date_raw",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1mmrhDataInner.attributeTypeMap;
    }

    public constructor() {
    }
}

