/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PremierSeasonDataInnerEventsInner } from '../models/V1PremierSeasonDataInnerEventsInner';
import { HttpFile } from '../http/http';

export class V1PremierSeasonDataInner {
    'id'?: string;
    'championshipEventId'?: string;
    'championshipPointsRequired'?: number;
    'startsAt'?: Date;
    'endsAt'?: Date;
    'enrollmentStartsAt'?: Date;
    'enrollmentEndsAt'?: Date;
    'events'?: Array<V1PremierSeasonDataInnerEventsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "championshipEventId",
            "baseName": "championship_event_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "championshipPointsRequired",
            "baseName": "championship_points_required",
            "type": "number",
            "format": ""
        },
        {
            "name": "startsAt",
            "baseName": "starts_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endsAt",
            "baseName": "ends_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "enrollmentStartsAt",
            "baseName": "enrollment_starts_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "enrollmentEndsAt",
            "baseName": "enrollment_ends_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<V1PremierSeasonDataInnerEventsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PremierSeasonDataInner.attributeTypeMap;
    }

    public constructor() {
    }
}

