/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TeamRoasterCustomization } from '../models/TeamRoasterCustomization';
import { V1PremierTeamDataMemberInner } from '../models/V1PremierTeamDataMemberInner';
import { V1PremierTeamDataPlacement } from '../models/V1PremierTeamDataPlacement';
import { V1PremierTeamDataStats } from '../models/V1PremierTeamDataStats';
import { HttpFile } from '../http/http';

export class V1PremierTeamData {
    'id'?: string;
    'name'?: string;
    'tag'?: string;
    'enrolled'?: boolean;
    'stats'?: V1PremierTeamDataStats;
    'placement'?: V1PremierTeamDataPlacement;
    'customization'?: TeamRoasterCustomization;
    'member'?: Array<V1PremierTeamDataMemberInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "enrolled",
            "baseName": "enrolled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "stats",
            "baseName": "stats",
            "type": "V1PremierTeamDataStats",
            "format": ""
        },
        {
            "name": "placement",
            "baseName": "placement",
            "type": "V1PremierTeamDataPlacement",
            "format": ""
        },
        {
            "name": "customization",
            "baseName": "customization",
            "type": "TeamRoasterCustomization",
            "format": ""
        },
        {
            "name": "member",
            "baseName": "member",
            "type": "Array<V1PremierTeamDataMemberInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PremierTeamData.attributeTypeMap;
    }

    public constructor() {
    }
}

