/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1PartialPremierTeam } from '../models/V1PartialPremierTeam';
import { HttpFile } from '../http/http';

export class V1PremierLeaderboard {
    'status'?: number;
    'data'?: Array<V1PartialPremierTeam>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<V1PartialPremierTeam>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PremierLeaderboard.attributeTypeMap;
    }

    public constructor() {
    }
}

