/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V1PremierTeamDataPlacement {
    'points'?: number;
    'conference'?: string;
    'division'?: number;
    'place'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "points",
            "baseName": "points",
            "type": "number",
            "format": ""
        },
        {
            "name": "conference",
            "baseName": "conference",
            "type": "string",
            "format": ""
        },
        {
            "name": "division",
            "baseName": "division",
            "type": "number",
            "format": ""
        },
        {
            "name": "place",
            "baseName": "place",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PremierTeamDataPlacement.attributeTypeMap;
    }

    public constructor() {
    }
}

