/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PremierSeasonsEventMapSelectionTypes } from '../models/PremierSeasonsEventMapSelectionTypes';
import { V1PremierSeasonDataInnerEventsInnerMapSelectionMapsInner } from '../models/V1PremierSeasonDataInnerEventsInnerMapSelectionMapsInner';
import { HttpFile } from '../http/http';

export class V1PremierSeasonDataInnerEventsInnerMapSelection {
    'type'?: PremierSeasonsEventMapSelectionTypes;
    'maps'?: Array<V1PremierSeasonDataInnerEventsInnerMapSelectionMapsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PremierSeasonsEventMapSelectionTypes",
            "format": ""
        },
        {
            "name": "maps",
            "baseName": "maps",
            "type": "Array<V1PremierSeasonDataInnerEventsInnerMapSelectionMapsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PremierSeasonDataInnerEventsInnerMapSelection.attributeTypeMap;
    }

    public constructor() {
    }
}



