/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PremierSeasonsEventTypes } from '../models/PremierSeasonsEventTypes';
import { V1PremierSeasonDataInnerEventsInnerConferenceSchedulesInner } from '../models/V1PremierSeasonDataInnerEventsInnerConferenceSchedulesInner';
import { V1PremierSeasonDataInnerEventsInnerMapSelection } from '../models/V1PremierSeasonDataInnerEventsInnerMapSelection';
import { HttpFile } from '../http/http';

export class V1PremierSeasonDataInnerEventsInner {
    'id'?: string;
    'type'?: PremierSeasonsEventTypes;
    'startsAt'?: Date;
    'endsAt'?: Date;
    'conferenceSchedules'?: Array<V1PremierSeasonDataInnerEventsInnerConferenceSchedulesInner>;
    'mapSelection'?: V1PremierSeasonDataInnerEventsInnerMapSelection;
    'pointsRequiredToParticipate'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PremierSeasonsEventTypes",
            "format": ""
        },
        {
            "name": "startsAt",
            "baseName": "starts_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "endsAt",
            "baseName": "ends_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "conferenceSchedules",
            "baseName": "conference_schedules",
            "type": "Array<V1PremierSeasonDataInnerEventsInnerConferenceSchedulesInner>",
            "format": ""
        },
        {
            "name": "mapSelection",
            "baseName": "map_selection",
            "type": "V1PremierSeasonDataInnerEventsInnerMapSelection",
            "format": ""
        },
        {
            "name": "pointsRequiredToParticipate",
            "baseName": "points_required_to_participate",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1PremierSeasonDataInnerEventsInner.attributeTypeMap;
    }

    public constructor() {
    }
}



