/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class V1QueueStatusDataInnerGameRules {
    'overtimeWinByTwo'?: boolean;
    'allowLenientSurrender'?: boolean;
    'allowDropOut'?: boolean;
    'assignRandomAgents'?: boolean;
    'skipPregame'?: boolean;
    'allowOvertimeDrawVote'?: boolean;
    'overtimeWinByTwoCapped'?: boolean;
    'premierMode'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "overtimeWinByTwo",
            "baseName": "overtime_win_by_two",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowLenientSurrender",
            "baseName": "allow_lenient_surrender",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowDropOut",
            "baseName": "allow_drop_out",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "assignRandomAgents",
            "baseName": "assign_random_agents",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "skipPregame",
            "baseName": "skip_pregame",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowOvertimeDrawVote",
            "baseName": "allow_overtime_draw_vote",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "overtimeWinByTwoCapped",
            "baseName": "overtime_win_by_two_capped",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "premierMode",
            "baseName": "premier_mode",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1QueueStatusDataInnerGameRules.attributeTypeMap;
    }

    public constructor() {
    }
}

