/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Tiers } from '../models/Tiers';
import { V1QueueStatusDataInnerSkillDisparityInnerMaxTier } from '../models/V1QueueStatusDataInnerSkillDisparityInnerMaxTier';
import { HttpFile } from '../http/http';

export class V1QueueStatusDataInnerSkillDisparityInner {
    'tier'?: number;
    'name'?: Tiers;
    'maxTier'?: V1QueueStatusDataInnerSkillDisparityInnerMaxTier;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "tier",
            "baseName": "tier",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "Tiers",
            "format": ""
        },
        {
            "name": "maxTier",
            "baseName": "max_tier",
            "type": "V1QueueStatusDataInnerSkillDisparityInnerMaxTier",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1QueueStatusDataInnerSkillDisparityInner.attributeTypeMap;
    }

    public constructor() {
    }
}



