/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V1storefeaturedDataFeaturedBundle } from '../models/V1storefeaturedDataFeaturedBundle';
import { HttpFile } from '../http/http';

export class V1storefeaturedData {
    'featuredBundle'?: V1storefeaturedDataFeaturedBundle;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "featuredBundle",
            "baseName": "FeaturedBundle",
            "type": "V1storefeaturedDataFeaturedBundle",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V1storefeaturedData.attributeTypeMap;
    }

    public constructor() {
    }
}

