/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LeaderboardInner } from '../models/LeaderboardInner';
import { HttpFile } from '../http/http';

export class V2leaderboard {
    'lastUpdate'?: number;
    'nextUpdate'?: number;
    'totalPlayers'?: number;
    'radiantThreshold'?: number;
    'immortal3Threshold'?: number;
    'immortal2Threshold'?: number;
    'immortal1Threshold'?: number;
    'players'?: Array<LeaderboardInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lastUpdate",
            "baseName": "last_update",
            "type": "number",
            "format": ""
        },
        {
            "name": "nextUpdate",
            "baseName": "next_update",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalPlayers",
            "baseName": "total_players",
            "type": "number",
            "format": ""
        },
        {
            "name": "radiantThreshold",
            "baseName": "radiant_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "immortal3Threshold",
            "baseName": "immortal_3_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "immortal2Threshold",
            "baseName": "immortal_2_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "immortal1Threshold",
            "baseName": "immortal_1_threshold",
            "type": "number",
            "format": ""
        },
        {
            "name": "players",
            "baseName": "players",
            "type": "Array<LeaderboardInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2leaderboard.attributeTypeMap;
    }

    public constructor() {
    }
}

