/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2mmrDataBySeason } from '../models/V2mmrDataBySeason';
import { V2mmrDataCurrentData } from '../models/V2mmrDataCurrentData';
import { V2mmrDataHighestRank } from '../models/V2mmrDataHighestRank';
import { HttpFile } from '../http/http';

export class V2mmrData {
    'name'?: string | null;
    'tag'?: string | null;
    'currentData'?: V2mmrDataCurrentData;
    'highestRank'?: V2mmrDataHighestRank;
    'bySeason'?: V2mmrDataBySeason;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentData",
            "baseName": "current_data",
            "type": "V2mmrDataCurrentData",
            "format": ""
        },
        {
            "name": "highestRank",
            "baseName": "highest_rank",
            "type": "V2mmrDataHighestRank",
            "format": ""
        },
        {
            "name": "bySeason",
            "baseName": "by_season",
            "type": "V2mmrDataBySeason",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2mmrData.attributeTypeMap;
    }

    public constructor() {
    }
}

