/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BySeason } from '../models/BySeason';
import { HttpFile } from '../http/http';

export class V2mmrDataBySeason {
    'e6a3'?: BySeason;
    'e6a2'?: BySeason;
    'e6a1'?: BySeason;
    'e5a3'?: BySeason;
    'e5a2'?: BySeason;
    'e5a1'?: BySeason;
    'e4a3'?: BySeason;
    'e4a2'?: BySeason;
    'e4a1'?: BySeason;
    'e3a3'?: BySeason;
    'e3a2'?: BySeason;
    'e3a1'?: BySeason;
    'e2a3'?: BySeason;
    'e2a2'?: BySeason;
    'e2a1'?: BySeason;
    'e1a3'?: BySeason;
    'e1a2'?: BySeason;
    'e1a1'?: BySeason;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "e6a3",
            "baseName": "e6a3",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e6a2",
            "baseName": "e6a2",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e6a1",
            "baseName": "e6a1",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e5a3",
            "baseName": "e5a3",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e5a2",
            "baseName": "e5a2",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e5a1",
            "baseName": "e5a1",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e4a3",
            "baseName": "e4a3",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e4a2",
            "baseName": "e4a2",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e4a1",
            "baseName": "e4a1",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e3a3",
            "baseName": "e3a3",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e3a2",
            "baseName": "e3a2",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e3a1",
            "baseName": "e3a1",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e2a3",
            "baseName": "e2a3",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e2a2",
            "baseName": "e2a2",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e2a1",
            "baseName": "e2a1",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e1a3",
            "baseName": "e1a3",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e1a2",
            "baseName": "e1a2",
            "type": "BySeason",
            "format": ""
        },
        {
            "name": "e1a1",
            "baseName": "e1a1",
            "type": "BySeason",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2mmrDataBySeason.attributeTypeMap;
    }

    public constructor() {
    }
}

