/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2storeofferContentTier } from '../models/V2storeofferContentTier';
import { HttpFile } from '../http/http';

export class V2storeoffer {
    'offerId'?: string;
    'cost'?: number;
    'name'?: string;
    'icon'?: string | null;
    'type'?: V2storeofferTypeEnum;
    'skinId'?: string;
    'contentTier'?: V2storeofferContentTier;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "offerId",
            "baseName": "offer_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "cost",
            "baseName": "cost",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "V2storeofferTypeEnum",
            "format": ""
        },
        {
            "name": "skinId",
            "baseName": "skin_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "contentTier",
            "baseName": "content_tier",
            "type": "V2storeofferContentTier",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2storeoffer.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum V2storeofferTypeEnum {
    SkinLevel = 'skin_level',
    SkinChroma = 'skin_chroma',
    Buddy = 'buddy',
    Spray = 'spray',
    PlayerCard = 'player_card',
    PlayerTitle = 'player_title'
}

