/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { V2storeoffer } from '../models/V2storeoffer';
import { HttpFile } from '../http/http';

export class V2storeoffersData {
    'offers'?: Array<V2storeoffer>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "offers",
            "baseName": "offers",
            "type": "Array<V2storeoffer>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return V2storeoffersData.attributeTypeMap;
    }

    public constructor() {
    }
}

