/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ValorantV1ContentGet200ResponseActsInnerLocalizedNamesInner {
    'arAE'?: string;
    'deDE'?: string;
    'enGB'?: string;
    'enUS'?: string;
    'esES'?: string;
    'esMX'?: string;
    'frFR'?: string;
    'idID'?: string;
    'itIT'?: string;
    'jaJP'?: string;
    'koKR'?: string;
    'plPL'?: string;
    'ptBR'?: string;
    'ruRU'?: string;
    'thTH'?: string;
    'trTR'?: string;
    'viVN'?: string;
    'znCN'?: string;
    'znTW'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "arAE",
            "baseName": "ar-AE",
            "type": "string",
            "format": ""
        },
        {
            "name": "deDE",
            "baseName": "de-DE",
            "type": "string",
            "format": ""
        },
        {
            "name": "enGB",
            "baseName": "en-GB",
            "type": "string",
            "format": ""
        },
        {
            "name": "enUS",
            "baseName": "en-US",
            "type": "string",
            "format": ""
        },
        {
            "name": "esES",
            "baseName": "es-ES",
            "type": "string",
            "format": ""
        },
        {
            "name": "esMX",
            "baseName": "es-MX",
            "type": "string",
            "format": ""
        },
        {
            "name": "frFR",
            "baseName": "fr-FR",
            "type": "string",
            "format": ""
        },
        {
            "name": "idID",
            "baseName": "id-ID",
            "type": "string",
            "format": ""
        },
        {
            "name": "itIT",
            "baseName": "it-IT",
            "type": "string",
            "format": ""
        },
        {
            "name": "jaJP",
            "baseName": "ja-JP",
            "type": "string",
            "format": ""
        },
        {
            "name": "koKR",
            "baseName": "ko-KR",
            "type": "string",
            "format": ""
        },
        {
            "name": "plPL",
            "baseName": "pl-PL",
            "type": "string",
            "format": ""
        },
        {
            "name": "ptBR",
            "baseName": "pt-BR",
            "type": "string",
            "format": ""
        },
        {
            "name": "ruRU",
            "baseName": "ru-RU",
            "type": "string",
            "format": ""
        },
        {
            "name": "thTH",
            "baseName": "th-TH",
            "type": "string",
            "format": ""
        },
        {
            "name": "trTR",
            "baseName": "tr-TR",
            "type": "string",
            "format": ""
        },
        {
            "name": "viVN",
            "baseName": "vi-VN",
            "type": "string",
            "format": ""
        },
        {
            "name": "znCN",
            "baseName": "zn-CN",
            "type": "string",
            "format": ""
        },
        {
            "name": "znTW",
            "baseName": "zn-TW",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValorantV1ContentGet200ResponseActsInnerLocalizedNamesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

