/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValorantV1VersionAffinityGet200ResponseData } from '../models/ValorantV1VersionAffinityGet200ResponseData';
import { HttpFile } from '../http/http';

export class ValorantV1VersionAffinityGet200Response {
    'status'?: number;
    'data'?: ValorantV1VersionAffinityGet200ResponseData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "number",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "ValorantV1VersionAffinityGet200ResponseData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValorantV1VersionAffinityGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

