/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ValorantV1RawPostRequest {
    /**
    * Can also be an array
    */
    'type'?: string;
    'value'?: string;
    'region'?: string;
    'queries'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        },
        {
            "name": "region",
            "baseName": "region",
            "type": "string",
            "format": ""
        },
        {
            "name": "queries",
            "baseName": "queries",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValorantV1RawPostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

