/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ContentInner } from '../models/ContentInner';
import { ValorantV1ContentGet200ResponseActsInner } from '../models/ValorantV1ContentGet200ResponseActsInner';
import { HttpFile } from '../http/http';

export class ValorantV1ContentGet200Response {
    'version'?: string;
    'characters'?: Array<ContentInner>;
    'maps'?: Array<ContentInner>;
    'chromas'?: Array<ContentInner>;
    'skins'?: Array<ContentInner>;
    'skinLevels'?: Array<ContentInner>;
    'equips'?: Array<ContentInner>;
    'gameModes'?: Array<ContentInner>;
    'sprays'?: Array<ContentInner>;
    'sprayLevels'?: Array<ContentInner>;
    'charms'?: Array<ContentInner>;
    'charmLevels'?: Array<ContentInner>;
    'playerCards'?: Array<ContentInner>;
    'playerTitles'?: Array<ContentInner>;
    'acts'?: Array<ValorantV1ContentGet200ResponseActsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "characters",
            "baseName": "characters",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "maps",
            "baseName": "maps",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "chromas",
            "baseName": "chromas",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "skins",
            "baseName": "skins",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "skinLevels",
            "baseName": "skinLevels",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "equips",
            "baseName": "equips",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "gameModes",
            "baseName": "gameModes",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "sprays",
            "baseName": "sprays",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "sprayLevels",
            "baseName": "sprayLevels",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "charms",
            "baseName": "charms",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "charmLevels",
            "baseName": "charmLevels",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "playerCards",
            "baseName": "playerCards",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "playerTitles",
            "baseName": "playerTitles",
            "type": "Array<ContentInner>",
            "format": ""
        },
        {
            "name": "acts",
            "baseName": "acts",
            "type": "Array<ValorantV1ContentGet200ResponseActsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValorantV1ContentGet200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

