/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StatusInner } from '../models/StatusInner';
import { HttpFile } from '../http/http';

export class ValorantV1StatusAffinityGet200ResponseData {
    'maintenances'?: Array<StatusInner>;
    'incidents'?: Array<StatusInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "maintenances",
            "baseName": "maintenances",
            "type": "Array<StatusInner>",
            "format": ""
        },
        {
            "name": "incidents",
            "baseName": "incidents",
            "type": "Array<StatusInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValorantV1StatusAffinityGet200ResponseData.attributeTypeMap;
    }

    public constructor() {
    }
}

