/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ValorantV1ContentGet200ResponseActsInnerLocalizedNamesInner } from '../models/ValorantV1ContentGet200ResponseActsInnerLocalizedNamesInner';
import { HttpFile } from '../http/http';

export class ValorantV1ContentGet200ResponseActsInner {
    'name'?: string;
    'localizedNames'?: Array<ValorantV1ContentGet200ResponseActsInnerLocalizedNamesInner>;
    'id'?: string;
    'isActive'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "localizedNames",
            "baseName": "localizedNames",
            "type": "Array<ValorantV1ContentGet200ResponseActsInnerLocalizedNamesInner>",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "isActive",
            "baseName": "isActive",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ValorantV1ContentGet200ResponseActsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

